### ISSUE TITLE
Related menu sometimes duplicates section content?

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/kinderplatz-web#17]
In "Credentials" section, "staff" ends up being both a section link AND a related link. Should just be section link

Does something else link to staff elsewhere that causes it to end up in related?

**Comment by webmasterkai** [comment]
I think this is resolved now. It was added as a link but it shares the same section, so was also auto-added.

**Comment by bjornmeansbear** [comment]
looks fixed!
