### ISSUE TITLE
`<blockquotes>` are always using the purple for the side border color, should use section/current page color

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/kinderplatz-web#18]

**Comment by bjornmeansbear** [comment]
related to #10

**Comment by webmasterkai** [comment]
Where is an example block quote? is it in the markdown?

**Comment by bjornmeansbear** [comment]
I think I have it in a style somewhere maybe... but yeah, block quotes are in markdown of pages, so I need some way to style them on a per page basis, not just in the plain css... maybe I can declare something for them to inherit
