### ISSUE TITLE
Links in Enrichment programs MD file are hardlinks to full URL, not to internal pages? how to resolve?

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/kinderplatz-web#21]
fix in https://github.com/OOKB/kinderplatz-api/

**Comment by bjornmeansbear** [comment]
here: https://github.com/OOKB/kinderplatz-api/blob/main/content/pages/enrichment-programs.md — how to do links like this in the future? should this be yaml header info? something else? just links in the MD like this?

**Comment by webmasterkai** [comment]
Links in the MD like this is easiest for the moment. This isn't easily generated without some deeper thinking.

**Comment by bjornmeansbear** [comment]
okay cool, well, I'll try to fix the couple that exist — there aren't many so its not a big deal

**Comment by bjornmeansbear** [comment]
okay, well I fixed them in `md` I think, and that was pretty much the only page that had a bunch of hard coded links that I've seen so far...
