### ISSUE TITLE
Does "Terms" under tuition become its own page?

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/kinderplatz-web#6]

**Comment by webmasterkai** [comment]
Maybe? Once policies are removed it feels less necessary?

**Comment by webmasterkai** [comment]
This might be a good example to work through with them to demonstrate adding a page that is part of a section. The `slug` value will need to have the same root path as the parent section. In this case, something like `tuition/terms`.

**Comment by bjornmeansbear** [comment]
just leave this.
